name: CI

on:
  push:
    branches: [ main ]
    paths: [ "hangman-front/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "hangman-front/**" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        working-directory: ./hangman-front
        run: |
          ls
          npm ci
          npm run build --if-present
      - name: Upload Artifact (dependencies)
        uses: actions/upload-artifact@v4
        with:
          name: dependencies
          path: hangman-front/node_modules/
          include-hidden-files: true
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact (dependencies)
        uses: actions/download-artifact@v4
        with:
          name: dependencies
          path: hangman-front/node_modules
      - name: test
        working-directory: ./hangman-front
        run: |
          chmod -R +x node_modules
          npm test

  